export const posts = [
   {
      title: "Just a Standard Format Post.",
      text: "Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...",
      tags: ["Design", "Photography"],
      date: "December 15, 2017",
   },
   {
      title: "10 Interesting Facts About Caffeine.",
      text: "Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...",
      tags: ["Health"],
      date: "December 15, 2017",
      image: "https://picsum.photos/id/20/300",
   },
   {
      title: "No Sugar Oatmeal Cookies.",
      text: "Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...",
      tags: ["Cooking", "Health"],
      date: "December 15, 2017",
      image: "https://picsum.photos/id/25/300",
   },
   {
      title: "What Your Music Preference Says About You and Your Personality.",
      text: "Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...",
      tags: ["Music", "Lifestyle"],
      date: "December 15, 2017",
      image: "https://picsum.photos/id/30/300",
   },
   {
      title: "Visiting Theme Parks Improves Your Health.",
      text: "Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...",
      tags: ["Health", "Lifestyle"],
      date: "December 15, 2017",
      image: "https://picsum.photos/id/35/300",
   },
   {
      title: "Visiting Theme Parks Improves Your Health.",
      text: "Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...",
      tags: ["Health", "Lifestyle"],
      date: "December 15, 2017",
      image: "https://picsum.photos/id/40/300",
   },
   {
      title: "Visiting Theme Parks Improves Your Health.",
      text: "Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...",
      tags: ["Health", "Lifestyle"],
      date: "December 15, 2017",
   },
   {
      title: "Visiting Theme Parks Improves Your Health.",
      text: "Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...",
      tags: ["Health", "Lifestyle"],
      date: "December 15, 2017",
      image: "https://picsum.photos/id/50/300",
   },
   {
      title: "Visiting Theme Parks Improves Your Health.",
      text: "Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...",
      tags: ["Health", "Lifestyle"],
      date: "December 15, 2017",
      image: "https://picsum.photos/id/55/300",
   },
   {
      title: "Visiting Theme Parks Improves Your Health.",
      text: "Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...",
      tags: ["Health", "Lifestyle"],
      date: "December 15, 2017",
   },
   {
      title: "Visiting Theme Parks Improves Your Health.",
      text: "Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...",
      tags: ["Health", "Lifestyle"],
      date: "December 15, 2017",
      image: "https://picsum.photos/id/65/300",
   },
   {
      title: "Visiting Theme Parks Improves Your Health.",
      text: "Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...",
      tags: ["Health", "Lifestyle"],
      date: "December 15, 2017",
      image: "https://picsum.photos/id/70/300",
   },
   {
      title: "Visiting Theme Parks Improves Your Health.",
      text: "Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...",
      tags: ["Health", "Lifestyle"],
      date: "December 15, 2017",
      image: "https://picsum.photos/id/75/300",
   },
   {
      title: "Visiting Theme Parks Improves Your Health.",
      text: "Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...",
      tags: ["Health", "Lifestyle"],
      date: "December 15, 2017",
   },
   {
      title: "Visiting Theme Parks Improves Your Health.",
      text: "Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...",
      tags: ["Health", "Lifestyle"],
      date: "December 15, 2017",
      image: "https://picsum.photos/id/85/300",
   },
];
